# İş akışının adı
name: filmfull Listesi Oluşturucu

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla (Checkout)
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- DÜZELTİLMESİ GEREKEN ADIM BURASI ---
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          # 'requirements.txt' dosyasını okuması için '-r' bayrağı eklendi
          pip install -r requirements.txt

      - name: Betiği Çalıştır ve M3U Dosyasını Oluştur
        run: python deneme.py

      - name: Değişiklikleri Depoya Gönder (Commit & Push)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add yelon.m3u
          git diff --staged --quiet || git commit -m "Otomatik Güncelleme: M3U çalma listesi güncellendi"
          git push